### ISSUE TITLE
Training speed is slow?

### ISSUE THREAD

**Issue by ztf-ucas** [jik0730/Meta-SGD-pytorch#1]
Thanks for your remarkable work!
The training speed on miniImageNet dataset is so slow (~10s/episode), I find that the utilization rate is very high for CPU but very low for GPU. Does the CPU limits training speed?

**Comment by jik0730** [comment]
Hi, thanks for your comment!
Yes, CPU can limit training speed. In that case to speed up, I recommend two options.

1. If you use raw miniImageNet dataset, you would better pre-resize images to 84x84 before the actual training. I guess the resizing processing by torchvision in run-time is highly responsible to high CPU utilization.
2. If you set "num_inner_tasks" in params.json too high, you can reduce the number to 4 for 1-shot, and 2 for 5-shot. These are typical settings for training miniImageNet in MAML or Meta-SGD, as revealed in original papers.

Both of two options may reduce computational time a lot. Hope you figure it out!

**Comment by ztf-ucas** [comment]
> Hi, thanks for your comment!
> Yes, CPU can limit training speed. In that case to speed up, I recommend two options.
> 
> 1. If you use raw miniImageNet dataset, you would better pre-resize images to 84x84 before the actual training. I guess the resizing processing by torchvision in run-time is highly responsible to high CPU utilization.
> 2. If you set "num_inner_tasks" in params.json too high, you can reduce the number to 4 for 1-shot, and 2 for 5-shot. These are typical settings for training miniImageNet in MAML or Meta-SGD, as revealed in original papers.
> 
> Both of two options may reduce computational time a lot. Hope you figure it out!

Thank you very much! You are so enthusiastic ！
I will try these suggestions.
